"""
mitmproxy addon that intercepts AI API traffic, parses responses,
calculates costs and attributes requests to local processes.

Loaded via: mitmdump -s ai_capture.py --set connection_strategy=lazy
"""

from __future__ import annotations

import time
import json
import logging
from pathlib import Path

from mitmproxy import http, ctx

from claw_cost_daemon.storage import Storage
from claw_cost_daemon.cost_engine import CostEngine
from claw_cost_daemon.parsers.providers import (
    detect_provider,
    parse_response,
    is_ai_endpoint,
)
from claw_cost_daemon.process import attribute_connection

logger = logging.getLogger("claw_cost_daemon.capture")

# Track request timestamps for latency calculation
_pending: dict[int, float] = {}


class AICaptureAddon:
    """mitmproxy addon for AI API traffic monitoring."""

    def __init__(self):
        self.db_path = Path("~/.claw-cost-daemon/events.db").expanduser()
        self.proxy_port = 8080
        self.storage: Storage | None = None
        self.cost_engine: CostEngine | None = None
        self._session_start = time.time()

    def load(self, loader):
        """Register script options exposed via `--set`."""
        loader.add_option(
            "claw_cost_daemon_db_path",
            str,
            str(self.db_path),
            "SQLite database path for claw-cost-daemon events.",
        )
        loader.add_option(
            "claw_cost_daemon_proxy_port",
            int,
            self.proxy_port,
            "Listen port used by the claw-cost-daemon mitmproxy instance.",
        )

    def configure(self, updated):
        """Initialise storage after mitmproxy options are available."""
        db_path = Path(ctx.options.claw_cost_daemon_db_path).expanduser()
        proxy_port = int(ctx.options.claw_cost_daemon_proxy_port)

        if (
            self.storage is not None
            and self.cost_engine is not None
            and db_path == self.db_path
            and proxy_port == self.proxy_port
        ):
            return

        self.db_path = db_path
        self.proxy_port = proxy_port
        self.storage = Storage(str(self.db_path))
        self.storage.init()
        self.cost_engine = CostEngine(str(self.db_path))
        ctx.log.info(
            f"[claw-cost-daemon] Addon loaded | db={self.db_path} | proxy_port={self.proxy_port}"
        )

    def _is_own_traffic(self, flow: http.HTTPFlow) -> bool:
        """Skip traffic generated by the monitor itself."""
        client_peer = flow.client_conn.peername
        if client_peer:
            ip, port = client_peer[:2]
            # mitmproxy's own outbound connections go through its own proxy
            if port == self.proxy_port:
                return True
        return False

    def request(self, flow: http.HTTPFlow):
        """Track outgoing AI API requests."""
        if self._is_own_traffic(flow):
            return

        host = flow.request.pretty_host
        path = flow.request.path

        if not is_ai_endpoint(host, path):
            return

        # Store timestamp for latency calculation
        _pending[id(flow)] = time.time()

        content_type = flow.request.headers.get("content-type", "").lower()
        accept = flow.request.headers.get("accept", "").lower()
        body = flow.request.get_text(strict=False) if flow.request.content else ""
        if "text/event-stream" in accept or (
            "application/json" in content_type and '"stream":true' in body.replace(" ", "").lower()
        ):
            flow.metadata["claw_cost_daemon_streaming"] = True
            # Ask OpenAI-compatible APIs to include usage in the final stream chunk.
            if "application/json" in content_type and flow.request.content:
                try:
                    req = json.loads(body)
                    if isinstance(req, dict):
                        stream_options = req.get("stream_options")
                        if not isinstance(stream_options, dict):
                            stream_options = {}
                        if stream_options.get("include_usage") is not True:
                            stream_options["include_usage"] = True
                            req["stream_options"] = stream_options
                            flow.request.text = json.dumps(req)
                except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
                    pass

    def responseheaders(self, flow: http.HTTPFlow):
        """Capture streaming chunks while keeping pass-through behavior."""
        if self._is_own_traffic(flow):
            return

        host = flow.request.pretty_host
        path = flow.request.path
        if not is_ai_endpoint(host, path):
            return

        content_type = flow.response.headers.get("content-type", "").lower()
        if flow.metadata.get("claw_cost_daemon_streaming") or "text/event-stream" in content_type:
            flow.metadata["claw_cost_daemon_streaming"] = True
            tail = bytearray()
            flow.metadata["claw_cost_daemon_sse_tail"] = tail

            # mitmproxy expects a per-chunk transformer callback for streamed bodies.
            def capture_chunk(chunk: bytes) -> bytes:
                tail.extend(chunk)
                if len(tail) > 262144:
                    del tail[: len(tail) - 262144]
                return chunk

            flow.response.stream = capture_chunk
            ctx.log.info(f"[claw-cost-daemon] streaming capture | {host}{path}")

    def response(self, flow: http.HTTPFlow):
        """Parse AI API responses, calculate costs, log events."""
        if self._is_own_traffic(flow):
            return

        host = flow.request.pretty_host
        path = flow.request.path

        if not is_ai_endpoint(host, path):
            return

        start_ts = _pending.pop(id(flow), None)
        if start_ts is None:
            return

        latency_ms = (time.time() - start_ts) * 1000 if start_ts else 0

        # Detect provider
        provider = detect_provider(host)
        if not provider:
            provider = "unknown"

        # Get client port for process attribution
        client_port = 0
        try:
            client_peer = flow.client_conn.peername
            if client_peer:
                client_port = client_peer[1]
        except Exception:
            pass

        # Parse response body (streaming or buffered)
        is_sse = bool(flow.metadata.get("claw_cost_daemon_streaming"))
        if is_sse:
            tail = flow.metadata.get("claw_cost_daemon_sse_tail")
            response_body = bytes(tail) if isinstance(tail, (bytearray, bytes)) else b""
        else:
            response_body = flow.response.content or b""
        parsed = parse_response(provider, response_body, is_sse=is_sse)

        if "error" in parsed and parsed.get("error"):
            # Send to dead-letter queue
            self.storage.insert_dead_letter(
                raw_metadata=json.dumps({
                    "host": host,
                    "path": path,
                    "status": flow.response.status_code,
                    "provider": provider,
                }),
                error_reason=parsed["error"],
            )
            logger.debug("Dead-letter: %s / %s: %s", provider, path, parsed["error"])
            return

        model = parsed.get("model", "")
        input_tokens = parsed.get("input_tokens", 0)
        output_tokens = parsed.get("output_tokens", 0)
        total_tokens = parsed.get("total_tokens", input_tokens + output_tokens)
        native_cost = parsed.get("native_cost")

        # Streaming responses are forwarded chunk-by-chunk and may not expose usage.
        # Fallback to request model and zero-token accounting so requests still appear.
        if is_sse and not model and input_tokens == 0 and output_tokens == 0:
            try:
                req_body = flow.request.get_text(strict=False) if flow.request.content else ""
                req_json = json.loads(req_body) if req_body else {}
                model = req_json.get("model", "") if isinstance(req_json, dict) else ""
            except Exception:
                model = ""

        # Skip non-completion requests (e.g., model listings)
        if not model and input_tokens == 0 and output_tokens == 0:
            return

        # Calculate costs
        if self.storage is None or self.cost_engine is None:
            logger.error("Addon not configured before response hook ran")
            return

        costs = self.cost_engine.calculate(provider, model, input_tokens, output_tokens)

        # Prefer provider-reported native cost when available (e.g., OpenRouter),
        # because it already reflects exact billing rules beyond static price tables.
        try:
            if native_cost is not None:
                native_total = float(native_cost)
                if native_total >= 0:
                    costs["input_cost_usd"] = 0.0
                    costs["output_cost_usd"] = 0.0
                    costs["total_cost_usd"] = round(native_total, 8)
        except (TypeError, ValueError):
            pass

        # Process attribution
        proc_info = attribute_connection(client_port, host, 443)

        # Insert event
        event = {
            "ts": start_ts,
            "provider": provider,
            "host": host,
            "endpoint": path,
            "model": model or "unknown",
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "total_tokens": total_tokens,
            "input_cost_usd": costs["input_cost_usd"],
            "output_cost_usd": costs["output_cost_usd"],
            "total_cost_usd": costs["total_cost_usd"],
            "status_code": flow.response.status_code,
            "latency_ms": round(latency_ms, 1),
            "pid": proc_info.pid,
            "process_name": proc_info.process_name or "unknown",
            "cmdline": proc_info.cmdline,
            "attribution_confidence": proc_info.confidence,
        }

        try:
            self.storage.insert_event(**event)
            ctx.log.info(
                f"[claw-cost-daemon] {provider} | {model} | ${costs['total_cost_usd']:.6f} | "
                f"{proc_info.process_name or '?'} | {flow.response.status_code}"
            )
        except Exception as exc:
            logger.error("Failed to insert event: %s", exc, exc_info=True)


addons = [AICaptureAddon()]
